# fly.toml app configuration file generated for projectmiddleware on 2024-09-10T20:57:47-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'projectmiddleware'
primary_region = 'gru'

[build]
  dockerfile = "Dockerfile"

[[env]]
  PORT = 8080

[experimental]
cmd = ["mongod", "--ipv6"]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[mounts]]
  source = 'productiondb_storage'
  destination = "/app/data"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
