name: Test and Coverage Verification

on:
  pull_request:

jobs:
  coverage-verification:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Validate coverage
        run: ./gradlew jacocoProjectMiddleWareCoverageVerification

      - name: Generate Tests Report (If JUnit finds violations)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Middleware-Test-Report
          path: 'build/reports/tests/test/'

      - name: Upload Unit Tests Coverage Report (If JaCoCo finds violations)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Middleware-Coverage-Report
          path: 'build/reports/jacoco/test/html/'